name: Security

on:
  pull_request: {}
  push:
    branches: [ "master", "11560-feature-test" ]

permissions:
  contents: read

jobs:
  govulncheck:
    name: Vulnerabilities Scan
    runs-on: ubuntu-latest
    steps:
      - name: Scan for vulnerabilities in go code
        uses: golang/govulncheck-action@v1
        with:
          go-version-input: '1.20.6'
          check-latest: true
